server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**
        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/api/claims/**
          filters:
            - RewritePath=/api/claims(?<segment>/?.*), /api/v2/claims$\{segment}
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**    

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

keycloak:
  auth-server-url: http://keycloak:8080/auth
  realm: api-gateway-realm
  resource: api-gateway

logging:
  level:
    root: INFO
    com.healthcare.api_gateway: DEBUG
    org.springframework.security: DEBUG
