spring:
  application:
    name: member-service
  datasource:
    url: jdbc:postgresql://postgres:5432/members
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081