spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notifications
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8138

grpc:
  client:
    memberService:
      address: static://member-service-instance-one:9090
      negotiationType: plaintext  
      enable-keep-alive: true
      keep-alive-without-calls: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        record-exceptions:
          - io.grpc.StatusRuntimeException
          - java.lang.RuntimeException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.nio.channels.UnresolvedAddressException
    instances:
      memberService:
        base-config: default
        failure-rate-threshold: 60 

  retry:
    instances:
      memberService:
        max-attempts: 3
        wait-duration: 2s

  timelimiter:
    instances:
      memberService:
        timeout-duration: 10s

logging:
  level:
    com.healthcare.notification_service.service.MemberContactService: DEBUG
    io.github.resilience4j: DEBUG
    net.devh.boot.grpc: WARN      
