spring: 
  datasource:
    url: jdbc:postgresql://postgres:5432/members
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${secretKey}
    expiration-ms: 3600000
    issuer: security-service

server:
  port: 8099